#!/usr/bin/env bash
set -uo pipefail

export USER="yumiaoyi"
export HOME="/home/yumiaoyi"
export QS_ICON_THEME="Papirus"
export XDG_DATA_DIRS="/usr/share:/home/yumiaoyi/.local/share"
export QT_QPA_PLATFORMTHEME="qt5ct"

export QT_ENABLE_HIGHDPI_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR="1.5625"
export GDK_DPI_SCALE="1.5625"

quickshell -p /home/yumiaoyi/.config/quickshell/Anachord &>/tmp/anachord-greeter.log
